version: "3.9"

services:
  db:
    image: postgres:16
    container_name: teddy-database
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    container_name: redis-container
    restart: always
    environment:
      REDIS_PASSWORD: myredispassword
    ports:
      - "6379:6379"

  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-service
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=db
      - REDIS_HOST=redis
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - .env 

volumes:
  db_data:
