name: Teddy Open Finance Demo Action

on: ["push"]
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker
        run: |
          echo "NODE_ENV=test" >> $GITHUB_ENV
          docker compose -f ./docker-composer.yml up -d

      - name: Tear down Docker
        if: always()
        run: docker compose -f ./docker-composer.yml down
