name: Teddy Open Finance Demo Action

on: ["push"]
jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Run docker
        run: docker compose up -f docker-composer.yml -d

      
